name: .NET Framework
on: 
    push:
    pull_request:
      branches:
        - main

jobs:
  build:
    
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
        
      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@v1.0.2
       
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
     
      - name: Restore NuGet Packages
        run: nuget restore LeoCorpLibrary.sln
 
      - name: Build and Publish Library
        run: msbuild LeoCorpLibrary.sln /p:Configuration=Release
